language: python

python:
  - "3.6"
  
env:
  - export FLASK_ENV ="development"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  
  - psql -c "CREATE ROLE james WITH createdb login PASSWORD 'andela';" -U postgres
  - psql -c 'CREATE DATABASE testchallenge3 owner james' -U postgres
    
# command to run tests
script:
  - pytest --cov=app/v2/ 

# Running coverals
after_success:
  - coveralls

#diasble notifications
notifications:
  email: false
